# Obtained from:
# https://medium.com/permutive/optimized-docker-builds-for-haskell-76a9808eb10b
# Reddit thread:
# https://www.reddit.com/r/haskell/comments/cl5uod/optimized_docker_builds_for_haskell/

# Loosely based on https://www.fpcomplete.com/blog/2017/12/building-haskell-apps-with-docker
FROM fpco/stack-build:lts-13.27 as dependencies
RUN mkdir -p /opt/build
WORKDIR /opt/build

# GHC dynamically links its compilation targets to lib gmp
RUN apt-get update \
  && apt-get download libgmp10
RUN mv libgmp*.deb libgmp.deb
RUN apt-get -y install libpq5

COPY . /opt/build/
RUN stack build --system-ghc --dependencies-only

# -------------------------------------------------------------------------------------------
FROM fpco/stack-build:lts-13.27

# TODO Copy compiled dependencies from previous stage
COPY --from=dependencies /root/.stack /root/.stack

